

const ENG = [
    '69',
    '666',
    '1cup',
    '2girls',
    '2girls1cup',
    '4r5e',
    '5h1t',
    'abortion',
    'ahole',
    'aids',
    'anal',
    'anal sex',
    'analsex',
    'angrydragon',
    'angrydragons',
    'angrypenguin',
    'angrypenguins',
    'angrypirate',
    'angrypirates',
    'anus',
    'apeshit',
    'ar5e',
    'arrse',
    'arse',
    'arsehole',
    'artard',
    'askhole',
    'ass',
    'ass 2 ass',
    'ass hole',
    'ass kisser',
    'ass licker',
    'ass lover',
    'ass man',
    'ass master',
    'ass pirate',
    'ass rapage',
    'ass rape',
    'ass raper',
    'ass to ass',
    'ass wipe',
    'assbag',
    'assbandit',
    'assbanger',
    'assberger',
    'assburger',
    'assclown',
    'asscock',
    'asses',
    'assface',
    'assfuck',
    'assfucker',
    'assfukker',
    'asshat',
    'asshead',
    'asshole',
    'asshopper',
    'assjacker',
    'asslicker',
    'assmunch',
    'asswhole',
    'asswipe',
    'aunt flo',
    'b000bs',
    'b00bs',
    'b17ch',
    'b1tch',
    'bag',
    'ballbag',
    'ballsack',
    'bampot',
    'bang',
    'bastard',
    'basterd',
    'bastich',
    'bean count',
    'beaner',
    'beastial',
    'beastiality',
    'beat it',
    'beat off',
    'beaver',
    'beavers',
    'beeyotch',
    'betch',
    'beyotch',
    'bfe',
    'bi sexual',
    'bi sexuals',
    'biatch',
    'bigmuffpi',
    'biotch',
    'bisexual',
    'bisexuality',
    'bisexuals',
    'bitch',
    'bitched',
    'bitches',
    'bitchin',
    'bitching',
    'bizatch',
    'blackie',
    'blackies',
    'block',
    'bloody hell',
    'blow',
    'blow job',
    'blow wad',
    'blowjob',
    'boff',
    'boffing',
    'boffs',
    'boink',
    'boinking',
    'boinks',
    'boiolas',
    'bollick',
    'bollock',
    'bondage',
    'boner',
    'boners',
    'bong',
    'boob',
    'boobies',
    'boobs',
    'booty',
    'boy2boy',
    'boy4boy',
    'boyforboy',
    'boyonboy',
    'boys2boys',
    'boys4boys',
    'boysforboys',
    'boysonboys',
    'boytoboy',
    'brothel',
    'brothels',
    'brotherfucker',
    'buceta',
    'bugger',
    'bugger ',
    'buggered',
    'buggery',
    'bukake',
    'bullshit',
    'bumblefuck',
    'bumfuck',
    'bung',
    'bunghole',
    'bush',
    'bushpig',
    'but',
    'but plug',
    'butplug',
    'butsecks',
    'butsekks',
    'butseks',
    'butsex',
    'butt',
    'buttfuck',
    'buttfucka',
    'buttfucker',
    'butthole',
    'buttmuch',
    'buttmunch',
    'buttplug',
    'buttsecks',
    'buttsekks',
    'buttseks',
    'buttsex',
    'buttweed',
    'c0ck',
    'c0cksucker',
    'cabron',
    'camel toe',
    'camel toes',
    'cameltoe',
    'canabis',
    'cannabis',
    'carpet muncher',
    'castrate',
    'castrates',
    'castration',
    'cawk',
    'chank',
    'cheesedick',
    'chick2chick',
    'chick4chick',
    'chickforchick',
    'chickonchick',
    'chicks2chicks',
    'chicks4chicks',
    'chicksforchicks',
    'chicksonchicks',
    'chickstochicks',
    'chicktochick',
    'chinc',
    'chink',
    'chinks',
    'choad',
    'choads',
    'chode',
    'cipa',
    'circlejerk',
    'circlejerks',
    'cl1t',
    'cleavelandsteemer',
    'cleveland',
    'clevelandsteamer',
    'clevelandsteemer',
    'clit',
    'clitoris',
    'clitoris    ', 
    'clits',
    'clusterfuck',
    'cock',
    'cock block',
    'cock suck',
    'cockblock',
    'cockface',
    'cockfucker',
    'cockfucklutated',
    'cockhead',
    'cockmaster',
    'cockmunch',
    'cockmuncher',
    'cockpenis',
    'cockring',
    'cocks',
    'cocksuck',
    'cocksucker',
    'cocksuka',
    'cocksukka',
    'cok',
    'cokmuncher',
    'coksucka',
    'comestain',
    'condom',
    'condoms',
    'coochie',
    'coon',
    'coons',
    'cooter',
    'copulated',
    'copulates',
    'copulating',
    'copulation',
    'corn',
    'corn_hole',
    'cornhole',
    'cornholes',
    'cr4p',
    'crap',
    'crapping',
    'craps',
    'cream',
    'creampie',
    'crotch',
    'crotches',
    'cum',
    'cumming',
    'cums',
    'cumshot',
    'cumstain',
    'cumtart',
    'cunnilingus',
    'cunt',
    'cuntbag',
    'cunthole',
    'cuntilingis',
    'cuntilingus',
    'cunts',
    'cuntulingis',
    'cuntulingus',
    'd1ck',
    'dabitch',
    'dago',
    'dammit',
    'damn',
    'damned',
    'dance',
    'darkie',
    'darkies',
    'darky',
    'deep',
    'deepthroat',
    'defecate',
    'defecates',
    'defecating',
    'defecation',
    'deggo',
    'diaf',
    'diarea',
    'diarhea',
    'diarrhea',
    'dick',
    'dickhead',
    'dickhole',
    'dickring',
    'dicks',
    'dicksucker',
    'dicksuckers',
    'dicksucking',
    'dicksucks',
    'dickwad',
    'dickweed',
    'dickwod',
    'dik',
    'dike',
    'dikes',
    'dildo',
    'dildoe',
    'dildoes',
    'dildos',
    'dilligaf',
    'dingleberry',
    'dipshit',
    'dirsa',
    'dlck',
    'dog',
    'doggin',
    'doggystyle',
    'dogshit',
    'domination',
    'dominatrix',
    'donkey',
    'donkeyribber',
    'dook',
    'doosh',
    'dork',
    'dorks',
    'douche',
    'douchebag',
    'douchebags',
    'douchejob',
    'douchejobs',
    'douches',
    'douchewaffle',
    'duche',
    'dumass',
    'dumb',
    'dumb fuck',
    'dumbass',
    'dumbfuc',
    'dumbfuck',
    'dumbshit',
    'dumdfuk',
    'dumfuck',
    'dumshit',
    'dyke',
    'dykes',
    'ead',
    'eat me',
    'ejaculat',
    'ejaculate',
    'ejaculated',
    'ejaculates',
    'ejaculation',
    'ejakulat',
    'ejakulate',
    'enema',
    'enemas',
    'enima',
    'enimas',
    'epeen',
    'epenis',
    'erect',
    'erection',
    'erekshun',
    'erotic',
    'eroticism',
    'f0x0r',
    'f0xx0r',
    'fack',
    'facker',
    'facking',
    'fag',
    'fagbag',
    'faggit',
    'faggitt',
    'faggot',
    'faggots',
    'faghag',
    'fags',
    'fagtard',
    'fannyflaps',
    'fannyfucker',
    'fart',
    'farting',
    'farts',
    'fatass',
    'fck',
    'fcker',
    'fckers',
    'fcking',
    'fcks',
    'fcuk',
    'fcuker',
    'fcuking',
    'feck',
    'fecker',
    'felch',
    'felched',
    'felcher',
    'felches',
    'felching',
    'fellate',
    'fellatio',
    'feltch',
    'feltched',
    'feltcher',
    'feltches',
    'feltching',
    'fetish',
    'fetishes',
    'finger',
    'fingering',
    'fisting',
    'flog',
    'flogging',
    'flogs',
    'fook',
    'fooker',
    'foreskin',
    'forked',
    'fornicate',
    'fornicates',
    'fornicating',
    'fornication',
    'frigging',
    'frottage',
    'fubar',
    'fuck',
    'fucka',
    'fuckas',
    'fuckass',
    'fucked',
    'fuckedup',
    'fucker',
    'fuckers',
    'fuckface',
    'fuckfaces',
    'fuckhead',
    'fuckhole',
    'fuckhouse',
    'fuckin',
    'fucking',
    'fuckingshitmotherfucker',
    'fucknugget',
    'fucks',
    'fucktard',
    'fuckwad',
    'fuckwhit',
    'fuckwit',
    'fuckyou',
    'fucndork',
    'fudgepacker',
    'fudgepacking',
    'fugly',
    'fuk',
    'fuken',
    'fuker',
    'fukker',
    'fukkin',
    'fukwhit',
    'fukwit',
    'fuq',
    'fuqed',
    'fuqing',
    'fuqs',
    'fux',
    'fux0r',
    'fuxx0r',
    'gang bang',
    'gangbang',
    'gangbanger',
    'gangbangers',
    'gangbanging',
    'gangbangs',
    'ganja',
    'gay',
    'gaydar',
    'gays',
    'gaytard',
    'gaywad',
    'genital',
    'genitalia',
    'genitals',
    'gerbiling',
    'ghey',
    'girl2girl',
    'girl4girl',
    'girlforgirl',
    'girlongirl',
    'girls2girls',
    'girls4girls',
    'girlsforgirls',
    'girlsongirls',
    'girlstogirls',
    'girltogirl',
    'gloryhole',
    'goatse',
    'gobshit',
    'gobshite',
    'gobtheknob',
    'goddam',
    'goddammit',
    'goddamn',
    'goddamned',
    'goddamnit',
    'gooch',
    'gook',
    'gooks',
    'groe',
    'gspot',
    'gtfo',
    'gubb',
    'gummer',
    'guppy',
    'guy2guy',
    'guy4guy',
    'guyforguy',
    'guyonguy',
    'guys2guys',
    'guys4guys',
    'guysforguys',
    'guysonguys',
    'guystoguys',
    'guytoguy',
    'gyfs',
    'hair pie',
    'hairpie',
    'hairpies',
    'hairy bush',
    'hand',
    'handjob',
    'harbl',
    'hard on',
    'hardon',
    'hardons',
    'hell',
    'hentai',
    'heroin',
    'herpes',
    'herps',
    'hick',
    'hiv',
    'ho',
    'hoare',
    'hoe',
    'hoebag',
    'hoer',
    'hoes',
    'hole',
    'homo',
    'homos',
    'homosexual',
    'homosexuality',
    'homosexuals',
    'honkee',
    'honkey',
    'honkie',
    'honkies',
    'honky',
    'hoochie',
    'hooker',
    'hookers',
    'hore',
    'horney',
    'hornie',
    'horny',
    'horseshit',
    'hosebeast',
    'hot',
    'hotcarl',
    'hotkarl',
    'hummer',
    'hump',
    'humping',
    'humps',
    'hymen',
    'i like ass',
    'i love ass',
    'i love tit',
    'i love tits',
    'iluvsnatch',
    'incest',
    'ip freely',
    'itard',
    'jack',
    'jack off',
    'jackass',
    'jackingoff',
    'jackoff',
    'jap',
    'japs',
    'jerk off',
    'jerkoff',
    'jesusfreak',
    'jewbag',
    'jewboy',
    'jiga',
    'jigaboo',
    'jigga',
    'jiggaboo',
    'jis',
    'jism',
    'jiz',
    'jizm',
    'jizz',
    'job',
    'junglebunny',
    'jysm',
    'kawk',
    'khunt',
    'kike',
    'kikes',
    'kinky',
    'kkk',
    'klit',
    'knob',
    'knobjocky',
    'knobjokey',
    'knockers',
    'kooch',
    'koolie',
    'koolielicker',
    'koolies',
    'kootch',
    'kukluxklan',
    'kunt',
    'kyke',
    'l3itch',
    'labia',
    'lap',
    'lapdance',
    'lelo',
    'lemonparty',
    'lesbian',
    'lesbians',
    'lesbifriends',
    'lesbo',
    'lesbos',
    'leyed',
    'lez',
    'lezzie',
    'lichercunt',
    'lick ass',
    'lick myass',
    'lick tit',
    'lickbeaver',
    'lickcarpet',
    'lickdick',
    'lickherass',
    'lickherpie',
    'lickmy ass',
    'lickpussy',
    'like ass',
    'like tit',
    'limpdick',
    'lingerie',
    'llello',
    'lleyed',
    'loltard',
    'love ass',
    'love juice',
    'love tit',
    'lovehole',
    'lsd',
    'lucifer',
    'lumpkin',
    'm0f0',
    'm0fo',
    'm45terbate',
    'ma5terb8',
    'ma5terbate',
    'mack',
    'mammaries',
    'man2man',
    'man4man',
    'mandingo',
    'manforman',
    'mangina',
    'manonman',
    'mantoman',
    'marijuana',
    'masochism',
    'masochist',
    'masterb8',
    'masterbat3',
    'masterbate',
    'masterbates',
    'masterbating',
    'masterbation',
    'masterbations',
    'masturbate',
    'masturbates',
    'masturbating',
    'masturbation',
    'meatcurtain',
    'men2men',
    'men4men',
    'menformen',
    'menonmen',
    'mentomen',
    'milf',
    'minge',
    'mistress',
    'mof0',
    'mofo',
    'motha',
    'motherfuck',
    'motherfucka',
    'motherfuckas',
    'motherfucked',
    'motherfucker',
    'motherfuckers',
    'motherfucking',
    'motherfuckka',
    'muff',
    'muff diver',
    'muffdiver',
    'muffdiving',
    'munch',
    'mung',
    'mutha',
    'muther',
    'muzza',
    'my ass',
    'n1gga',
    'n1gger',
    'naked',
    'nambla',
    'nards',
    'nazi',
    'nazies',
    'nazis',
    'necrophile',
    'necrophiles',
    'necrophilia',
    'necrophiliac',
    'negro',
    'neonazi',
    'nice ass',
    'nig',
    'nigg3r',
    'nigg4h',
    'nigga',
    'niggah',
    'niggas',
    'niggaz',
    'nigger',
    'niggers',
    'nigglet',
    'niglet',
    'nippies',
    'nipple',
    'nips',
    'nobhead',
    'nobjockey',
    'nobjocky',
    'nobjokey',
    'nookey',
    'nookie',
    'noshit',
    'nude',
    'nudes',
    'nudity',
    'numbnuts',
    'nut bag',
    'nut lick',
    'nut lover',
    'nut sack',
    'nut suck',
    'nutnyamouth',
    'nutnyomouth',
    'nuts',
    'nutsack',
    'nutstains',
    'nymph',
    'nympho',
    'nymphomania',
    'nymphomaniac',
    'nymphomaniacs',
    'nymphos',
    'oral',
    'orgasm',
    'orgasmic',
    'orgasms',
    'orgi',
    'orgiastic',
    'orgies',
    'orgy',
    'paedophile',
    'panooch',
    'panties',
    'panty',
    'patootie',
    'pecker',
    'peckerhead',
    'peckers',
    'pedophile',
    'pedophiles',
    'pedophilia',
    'peepshow',
    'peepshows',
    'pen15',
    'penii',
    'penis',
    'penises',
    'penisfucker',
    'perve',
    'perversion',
    'pervert',
    'perverted',
    'perverts',
    'phat',
    'phile',
    'philes',
    'philia',
    'phuck',
    'phucker',
    'phuckers',
    'phucking',
    'phucks',
    'phuk',
    'phuker',
    'phukers',
    'phuking',
    'phuks',
    'phuq',
    'phuqer',
    'phuqers',
    'phuqing',
    'phuqs',
    'pie',
    'pigfucker',
    'pimpis',
    'piss',
    'pissant',
    'pissed',
    'pisser',
    'pisses',
    'pissfart',
    'pissflaps',
    'pissing',
    'pocket',
    'poke',
    'poon',
    'poon eater',
    'poon tang',
    'poonani',
    'poonanny',
    'poonany',
    'poonj',
    'poonjab',
    'poonjabie',
    'poonjaby',
    'poontang',
    'poop',
    'poopchute',
    'poot',
    'porchmonkey',
    'porking',
    'porks',
    'porn',
    'porno',
    'prick',
    'pricks',
    'prostitot',
    'pube',
    'pubes',
    'pubic',
    'pud',
    'pudd',
    'puds',
    'punani',
    'punanni',
    'punanny',
    'punta',
    'puntang',
    'pusse',
    'pussi',
    'pussies',
    'pussy',
    'puta',
    'puto',
    'qeef',
    'qfmft',
    'qq more',
    'quafe',
    'quap',
    'quatch',
    'queef',
    'queefe',
    'queefed',
    'queefing',
    'queer',
    'queerbait',
    'queermo',
    'queers',
    'queev',
    'quefe',
    'queif',
    'quief',
    'quif',
    'quiff',
    'quim',
    'quim nuts',
    'qweef',
    'racial',
    'racism',
    'racist',
    'racists',
    'rape',
    'raped',
    'raper',
    'raping',
    'rapist',
    'redtide',
    'reefer',
    'renob',
    'retard',
    'ricockulous',
    'rim job',
    'rimjaw',
    'rimjob',
    'rimjobs',
    'rimming',
    'roofie',
    'rtard',
    'rtfm',
    'rubbers',
    'rump',
    'rumpranger',
    'rumprider',
    'rumps',
    'rustytrombone',
    'sadism',
    'sadist',
    'sadomasochism',
    'sand nigger',
    'sandnigga',
    'sandniggas',
    'sandnigger',
    'sandniggers',
    'sapphic',
    'sappho',
    'sapphos',
    'satan',
    'scatological',
    'scheiss',
    'scheisse',
    'schlong',
    'schlonging',
    'schlongs',
    'schtup',
    'schtupp',
    'schtupping',
    'schtups',
    'screw',
    'screw me',
    'screw this',
    'screw you',
    'screwed',
    'screwer',
    'screwing',
    'screws',
    'screwyou',
    'scroat',
    'scrog',
    'scrote',
    'scrotum',
    'secks',
    'sekks',
    'seks',
    'semen',
    'sex',
    'sexed',
    'sexking',
    'sexkitten',
    'sexmachine',
    'sexqueen',
    'sexual',
    'sexuality',
    'sexy',
    'sexybitch',
    'sexybitches',
    'sh1t',
    'shag',
    'shagger',
    'shaggin',
    'shagging',
    'shart',
    'shemale',
    'shit',
    'shitdick',
    'shite',
    'shited',
    'shitey',
    'shitface',
    'shitfaced',
    'shitfuck',
    'shithead',
    'shitlist',
    'shits',
    'shitt',
    'shitted',
    'shitter',
    'shittiest',
    'shitting',
    'shitts',
    'shitty',
    'shiznits',
    'shotacon',
    'shotakon',
    'shyte',
    'sickass',
    'sixtynine',
    'sixtynining',
    'skank',
    'skeet',
    'sketell',
    'sko',
    'skrew',
    'skrewing',
    'skrews',
    'slant eye',
    'slanteyes',
    'slattern',
    'slave',
    'slaves',
    'slopehead',
    'slopeheads',
    'slut',
    'slutbag',
    'slutpuppy',
    'sluts',
    'slutty',
    'slutwhore',
    'smegma',
    'smut',
    'snatch',
    'snatches',
    'soddom',
    'sodom',
    'sodomist',
    'sodomists',
    'sodomize',
    'sodomized',
    'sodomizing',
    'sodomy',
    'sonnofabitch',
    'sonnovabitch',
    'sonnuvabitch',
    'sonofabitch',
    'spank',
    'spanked',
    'spanking',
    'spanks',
    'spearchucker',
    'spearchuckers',
    'sperm',
    'spermicidal',
    'spermjuice',
    'sphincter',
    'spic',
    'spick',
    'spicks',
    'spics',
    'spik',
    'spiks',
    'spooge',
    'stank ho',
    'stankpuss',
    'steamer',
    'stfu',
    'stiffie',
    'stiffy',
    'stud',
    'studs',
    'submissive',
    'submissives',
    'suck',
    'suck ass',
    'sucks ass',
    'swinger',
    'swingers',
    't1tt1e5',
    't1tties',
    'take a dump',
    'takeadump',
    'tar baby',
    'tarbaby',
    'tard',
    'teabaggin',
    'teabagging',
    'teen2teen',
    'teen4teen',
    'teenforteen',
    'teenonteen',
    'teens2teens',
    'teens4teens',
    'teensforteens',
    'teensonteens',
    'teenstoteens',
    'teentoteen',
    'teets',
    'teez',
    'testes',
    'testical',
    'testicals',
    'testicle',
    'testicles',
    'threesome',
    'throat',
    'thundercunt',
    'tiddie',
    'tiddy',
    'tit',
    'titandass',
    'titbabe',
    'titball',
    'titfuck',
    'tits',
    'titsandass',
    'titt',
    'tittie',
    'tittie5',
    'tittiefucker',
    'titties',
    'titts',
    'titty',
    'tittyfuck',
    'tittywank',
    'titwank',
    'toke',
    'toss salad',
    'tramp',
    'tramps',
    'tranny',
    'transexual',
    'transexuals',
    'transvestite',
    'transvestites',
    'tubgirl',
    'turd',
    'tw4t',
    'twat',
    'twathead',
    'twatlips',
    'twats',
    'twatty',
    'twunt',
    'twunter',
    'ufia',
    'umfriend',
    'underwear',
    'up yours',
    'upyours',
    'upyourz',
    'urinate',
    'urinated',
    'urinates',
    'urinating',
    'urination',
    'urine',
    'vaffanculo',
    'vag',
    'vagina',
    'vaginal',
    'vaginas',
    'vaginer',
    'vagitarian',
    'vagoo',
    'vagy',
    'vajayjay',
    'viagra',
    'vibrator',
    'virgin',
    'virginity',
    'virgins',
    'voyeur',
    'voyeurism',
    'voyeurs',
    'vulva',
    'w00se',
    'wackedoff',
    'wackoff',
    'wad blower',
    'wad lover',
    'wad sucker',
    'wadblower',
    'wadlover',
    'wadsucker',
    'waffle',
    'wang',
    'wank',
    'wanker',
    'wanky',
    'wetback',
    'wetbacks',
    'wetdream',
    'wetdreams',
    'whackedoff',
    'whackoff',
    'whigger',
    'whip',
    'whipped',
    'whipping',
    'whips',
    'whiz',
    'whoe',
    'whore',
    'whored',
    'whorehouse',
    'whores',
    'whoring',
    'wigger',
    'willies',
    'wog',
    'wogged',
    'woggy',
    'wogs',
    'woman2woman',
    'woman4woman',
    'womanforwoman',
    'womanonwoman',
    'womantowoman',
    'women2women',
    'women4women',
    'womenforwomen',
    'womenonwomen',
    'womentowomen',
    'woof',
    'wop',
    'xx',
    'xxx',
    'yank',
    'yayo',
    'yeat',
    'yeet',
    'yeyo',
    'yiff',
    'yiffy',
    'yola',
    'yols',
    'yoni',
    'youaregay',
    'yourgay',
    'zipperhead',
    'zipperheads',
    'zorch',
]

const PTBR = [
    '24',
    '68',
    '69',
    '420',
    '666',
    '5 contra 1',
    '5 x 1',
    '5contra1',
    '5x1',
    'aborto',
    'abusar da massaneta',
    'abuso sexual',
    'afogar o ganso',
    'aguardente',
    'alcoice',
    'amarelar',
    'anel de couro',
    'aneldecouro',
    'aputa',
    'aputar',
    'aquenda',
    'armar a barraca',
    'atrasar a merda',
    'b4b4c4',
    'babaca',
    'babalu',
    'back',
    'badalo',
    'bagana',
    'bago',
    'bagui',
    'bagulho',
    'baitola',
    'baitolo',
    'ballcat',
    'banza',
    'banzo',
    'barroso',
    'baseado',
    'batedor',
    'bater punheta',
    'bater uma',
    'bateruma',
    'benga',
    'bicha',
    'bilau',
    'bimbo',
    'biqueura',
    'birinight',
    'biscate',
    'bitola',
    'boazura',
    'boceta',
    'bofe',
    'bofinho',
    'boga',
    'bolada no queixo',
    'bolete',
    'bolinho de estudante',
    'bomba',
    'boquete',
    'bordel',
    'botico',
    'branquelo',
    'braquiara',
    'brefa',
    'brioco',
    'bronha',
    'bronhas',
    'bubu',
    'buceta',
    'bucetada',
    'bumbum guloso',
    'burge',
    'burro',
    'cacete',
    'cacete armado',
    'cachorra',
    'caga',
    'Caga pau',
    'cagada',
    'cagam',
    'caganita',
    'cagar',
    'cagar pra dentro',
    'cague',
    'caja negra',
    'camisinha',
    'camuflar a cenoura',
    'cannabis',
    'capacete',
    'caposa',
    'caraca quente',
    'caraio',
    'caralho',
    'carcamano',
    'carne mijada',
    'casa da luz vermelha',
    'catzo',
    'cavala',
    'cavaloa',
    'cavalona',
    'cerveja',
    'chauleta',
    'chibata',
    'chinoca',
    'chonga',
    'chota',
    'chuca',
    'chucrute',
    'chuopeta',
    'chupada',
    'chupatilha',
    'chupisco',
    'cigarro',
    'clamangau',
    'clitarra',
    'cocaina',
    'cocota',
    'coito',
    'comer cu',
    'comercu',
    'cona',
    'consorte',
    'coquerim',
    'crack',
    'cu',
    'cunnilingus',
    'cuquete',
    'danada',
    'dar a bunda',
    'dar o cu',
    'dar um caldo',
    'darocu',
    'dedihadeira',
    'descargar a carga',
    'descascar a banana',
    'deslisar no quiabo',
    'despida',
    'despido',
    'devassa',
    'dread',
    'drogas',
    'empurrar merda',
    'enema',
    'enraber',
    'erva',
    'escapa a quarta',
    'esconder a cobra',
    'esconder o calango',
    'esfiha',
    'espada',
    'esperma',
    'estrangular o careca',
    'estuprar',
    'estupro',
    'excitar',
    'excremento',
    'faca cega',
    'fazer o feijoeiro',
    'fazer sexo',
    'fdp',
    'felatio',
    'ferro',
    'fezes',
    'filha da puta',
    'filhadaputa',
    'filho da puta',
    'filhodaputa',
    'fisha',
    'foda',
    'foda no rabo',
    'fodase',
    'foder',
    'fuder',
    'fuga de lua',
    'fulaca',
    'fuleco',
    'fuleira',
    'fulera',
    'fuleragem',
    'fumo',
    'furico',
    'galhinia',
    'ganja',
    'gargamelo',
    'garganta profunda',
    'garguela',
    'garota de programa',
    'gay',
    'giromba',
    'golete',
    'gorgota',
    'gravar',
    'grelinho ',
    'grelo',
    'guei',
    'guga',
    'gulosa',
    'guloso',
    'habib',
    'hemp',
    'homossexual',
    'incesto',
    'jaburu',
    'japa',
    'jeba',
    'jereba',
    'jogar dadinho',
    'kct',
    'kenga',
    'kralh0',
    'laranjada',
    'lesbiana',
    'lesbiano',
    'lilo',
    'macumbeiro',
    'mama',
    'mamar',
    'mangote',
    'marafa',
    'marafa',
    'marconha',
    'marolar',
    'masoquismo',
    'masoquista',
    'masturbar',
    'Matusquela',
    'meia nove',
    'meiameimeia',
    'meianove',
    'meladinha',
    'merda',
    'merdimbuca',
    'meritriz',
    'messalina',
    'minete',
    'molhar o biscoito',
    'motumbo',
    'mufa',
    'mulher de rua',
    'mulher porta de venda',
    'mussuba',
    'naba',
    'naja',
    'nalga',
    'nazista',
    'nba',
    'neca',
    'nesconha',
    'ninfomania',
    'nu',
    'nua',
    'nudez',
    'nudista',
    'nus',
    'oet',
    'olho da goiaba',
    'olhota',
    'onanismo',
    'onanista',
    'opio',
    'oral',
    'orgasmatico',
    'orgasmico',
    'orgasmo',
    'pacau',
    'pakalolo',
    'parrucha',
    'pau de burro',
    'pederastia',
    'pederastra',
    'pedofilia',
    'pedra preciosa',
    'peider',
    'peita',
    'peito',
    'pelanca',
    'pepeca',
    'peru',
    'pervinha',
    'peta',
    'petoka',
    'pica',
    'pica',
    'pichorra',
    'pika',
    'pila',
    'pileque',
    'pimboca',
    'pinga',
    'pingado',
    'pingola',
    'pinguelo',
    'piranha',
    'piriguete',
    'piroca',
    'pistola',
    'pistola',
    'pitoca',
    'poha',
    'polaca',
    'polaco',
    'porno',
    'pornografia',
    'portranca',
    'porva',
    'pota',
    'preservativo',
    'preventivo',
    'prostibulo',
    'prostituta',
    'punhado',
    'punheta',
    'punheteiro',
    'purra',
    'puta',
    'puteiro',
    'quebrar azulejo',
    'queimar a rosca',
    'quenga',
    'rabo',
    'rabo de saia',
    'racha ',
    'racista',
    'rampa',
    'rampeira',
    'rapariga',
    'raptar',
    'rapto',
    'renovar a porra',
    'rescofe',
    'roela',
    'rola',
    'sadista',
    'safira',
    'sarrar',
    'sativa',
    'se cagar',
    'se masturbar',
    'seio ',
    'seios',
    'semasturbar',
    'sentar na farinha',
    'ser foda',
    'sexo',
    'sexo oral',
    'sexooral',
    'sexopatia',
    'sexual',
    'shucruti',
    'siricutico',
    'sirigaita',
    'siririca',
    'soltar um barro',
    'sorvete de saquinho',
    'squick',
    'sugador',
    'Suruba',
    'suruba',
    'taba',
    'tabaco',
    'tara',
    'tarado',
    'testiculo',
    'tesuda',
    'tipa',
    'tira estresse',
    'tirar o atraso',
    'tirar porra do caralho',
    'titica',
    'transa ',
    'transar',
    'transsexual',
    'traveco',
    'travesti',
    'tribufu',
    'trompete',
    'tupiniquim',
    'vadia',
    'vai a merda',
    'vai cagar',
    'vai foder',
    'vai meter com o cu',
    'vai pro inferno',
    'vai pruca',
    'vai se foder',
    'vai te catar',
    'vai tomar na porra',
    'vai tomar no cu',
    'vai tomar no olho do seu cu',
    'vaifoder',
    'vaisefoder',
    'ver o sabugo com outro olho',
    'viaamerda',
    'viado',
    'vinte quatro',
    'vintequatro',
    'voyeur ',
    'voyeurismo',
    'vulva',
    'xana',
    'xaninha',
    'xavasca',
    'xereca',
    'xibiu',
    'xoxota',
    'xupeta',
    'xuranha',
    'zorato',
]

module.exports = {
    ENG,
    PTBR,
}